services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: kgbites_postgres
    environment:
      POSTGRES_DB: kgbites_db
      POSTGRES_USER: kgbites_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kgbites_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kgbites_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kgbites_user -d kgbites_db"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  kgbites_network:
    driver: bridge

volumes:
  postgres_data: